# Generated by Django 3.1.3 on 2020-12-01 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='target_total_amount',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[(1, 'carrito'), (2, 'pagado'), (3, 'entregado')], max_length=40),
        ),
    ]
